---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mashacor/gc-box.com/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp Router.php $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH