---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mashacor/gc-box.com/
    - /bin/cp -R clases $DEPLOYPATH
    - /bin/cp -R controllers $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp Router.php $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH